README.md, src/Connection.cpp
File descriptor belonging to event loop's semaphore need to be closed on exec, else the loaded program might use it inadvertently - when forking, the child process might interfere with the event loop.
=> Close file descriptor of event loop's semaphore on exec

include/sdbus-c++/Types.h, test/unittests/Types_test.cpp
Added a test example where sdbus::Struct fails to compile with clang (tested with clang 4 & 5):
```
| ../../git/test/unittests/Types_test.cpp:210:41: error: no matching constructor for initialization of 'sdbus::Struct<int32_t, std::string>' (aka 'Struct<int, basic_string<char> >')
|     sdbus::Struct<int32_t, std::string> valueStruct{value};
|                                         ^          ~~~~~~~
| ../../git/include/sdbus-c++/Types.h:94:11: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::tuple<int32_t, std::string>' (aka 'tuple<int, basic_string<char> >') to 'sdbus::Struct<int, std::__cxx11::basic_string<char> >' for 1st argument
|     class Struct
|           ^
| ../../git/include/sdbus-c++/Types.h:94:11: note: candidate …
```
=> Fix proposal for clang compilation issue

include/sdbus-c++/TypeTraits.h, include/sdbus-c++/Types.h
This makes the Variant API more robust (conversion operator is a sensitive thing) and helps fix problems with googlemock on x86_64, which inspects whether Variant can be converted to ulonglong for content-printing purposes, and that inspection ends up in a static_assert compilation error. Now googlemock just detects that there is no such conversion possible (because operator is there only strictly for a set of C++ types representing D-Bus types), and continues trying other options.
=> Make Variant conversion operator only present for true D-Bus types

src/Message.cpp
The fix for a memory leak, which occurs with an usage of sdbus::Variant.
=> Message: fix missing release of sd_bus_message

configure.ac, src/Connection.cpp, test/Makefile.am, test/integrationtests/AdaptorAndProxy_test.cpp, test/integrationtests/TestingAdaptor.h
The eventfd descriptor was forgotten to be read from by the consumer, causing poll to always signal readiness for reading.
=> Fix CPU hog on async methods

include/sdbus-c++/ConvenienceClasses.inl
Be explicit on qualification of the apply function from sdbus namespace, since gcc 7.3 now has two equally ranked candidates (std::apply, kicked in most likely via Koenig lookup, and sdbus::apply, implicitly present in the namespace) and throws ambiguity error.
=> Fix std::apply vs. sdbus::apply ambiguity error in gcc 7.3

stub-generator/BaseGenerator.cpp
E.g https://github.com/connectivity/connman-gnome/blob/master/common/connman-agent.xml
is missing "name" for method arguments.
This patch ensures that the valid code is generated for such a case.
=> stub-generator: fixed issue when <arg> in <method> does not have "name"

src/Types.cpp
Fixes #8
(cherry picked from commit f8bed4b0faa2c0a2bc7037f3a55105060d56dbdb)
=> - Rewind Message prior to access for peekValueType.

CMakeLists.txt
These options:
* shall rather come from the user instead of being hard-coded in the project build system,
* if kept hard-coded, they may cause unnecessary compilation errors, like in #28 , due to new (and not always useful, cf. discussion at https://github.com/boostorg/mpl/issues/31#issuecomment-368998776) warnings introduced by new versions of compilers.
Fixes #28 , as the warning (turned to error) there is issued by gcc 8 on a completely valid code.
=> Remove warnings-related compiler options from CMakeLists

README.md, doc/systemd-dbus-config.md
I was not able to run samples from scratch. After a while I found that there must be configuration files to grant access rights.
=> Add systemd and dbus config, e.g. to run samples in 'Using sdbus-c++ library'

include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Connection.h
Currently, sdbus-c++ cannot be integrated into foreign event loops, like gtk's or KDE's event loop - and therefore it's impossible to use sdbus-c++ in gtk/kde apps without sdbus-c++ creating an additional thread.
To solve this, sdbus-c++ needs to expose the sdbus' function `sd_bus_get_poll_data`. The result can then be polled for in the user's app or added as an event source to the event loop system the user is using (for example by using the gtk method `g_main_context_add_poll` in gtk apps).
This PR exposes this function and allows the user to process a single sdbus event (whenever the file descriptor signals).
=> Added ability to integrate with foreign event loops

CMakeLists.txt, cmake/LibsystemdExternalProject.cmake, include/sdbus-c++/ConvenienceApiClasses.h, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/IConnection.h, include/sdbus-c++/IObject.h, include/sdbus-c++/IProxy.h, include/sdbus-c++/Message.h, src/Connection.cpp, src/Connection.h, src/ConvenienceApiClasses.cpp, src/ISdBus.h, src/Message.cpp, src/Proxy.cpp, src/Proxy.h, src/SdBus.cpp, src/SdBus.h, tests/CMakeLists.txt, tests/integrationtests/AdaptorAndProxy_test.cpp, tests/integrationtests/TestingProxy.h, tests/integrationtests/proxy-glue.h, tests/unittests/mocks/SdBusMock.h, tools/xml2cpp-codegen/AdaptorGenerator.cpp, tools/xml2cpp-codegen/ProxyGenerator.cpp
Currently there is no possibility to specify the timeout value for asynchronous call. This pull request extends the functionality to add support for specifying custom timeout values for asynchronous calls.
=> Added support to specify custom timeout value for async DBus client call

include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Connection.h, src/ISdBus.h, src/SdBus.cpp, src/SdBus.h
The sd_bus C library provides the ability to open a connection to the system bus on a remote device using ssh. This type of connection is created using the `sd_bus_open_system_remote()` function. This PR adds the necessary plumbing to use this functionality in sdbus-cpp. A new connection creation method was added, `createRemoteSystemBusConnection()` which takes a single argument, the name of the host you'd like to connect to (ex. "user@192.168.1.1").
=> Added support for opening a connection to a remote system bus using ssh

include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Connection.h, src/ISdBus.h, src/SdBus.cpp, src/SdBus.h
Hello!
I added this method to get the unique name of a connection.  It is useful to access remote adapters on unnamed connection.
=> Add a method to retrieve the unique name of a connection

tools/xml2cpp-codegen/xml2cpp.cpp
fixes issue: https://github.com/Kistler-Group/sdbus-cpp/issues/83
=> sdbus-c++-xml2cpp: fixed file existence condition

src/Proxy.cpp, tests/integrationtests/AdaptorAndProxy_test.cpp, tests/integrationtests/TestingProxy.h
* Proxy::sdbus_signal_handler() needs to return 0 instead of 1 in
order to allow multiple proxies listening to a signal all being
triggered.
* Add test for emitting a signal to multiple proxies on same
connection.
=> Fix #93: Get signals working for multiple proxies.

tests/integrationtests/adaptor-glue.h
Recently, a support for method and signal parameter names in introspection was added to the library, but it requires `libsystemd` version 242+ to support it. So that, vtable is set up depending on its version:
https://github.com/Kistler-Group/sdbus-cpp/blob/master/src/VTableUtils.c#L73
However, we are running `libsystemd` 239 and our integration tests are failing, as they expect output with parameter names. Here is a patch that fixes `SdbusTestObject.AnswersXmlApiDescriptionViaIntrospectableInterface` test case to behave correctly depending on `libsystemd` version.
=> Fixed integration tests for libsystemd older than 242

src/Proxy.cpp
This should not be required in C++17 because there is an appropriate [class template deduction rule](https://en.cppreference.com/w/cpp/memory/weak_ptr/deduction_guides) which infers that it's going to be a `weak_ptr<T>` when constructing from a `shared_ptr<T>`. However, in clang/LLVM's libcxx C++ STL implementation this [only got implemented in May 2020](https://reviews.llvm.org/D69603).
Here's the failure (Fedora 31, clang 9.0.1):
```
[8/19] Building CXX object CMakeFiles/sdbus-c++-objlib.dir/src/Proxy.cpp.o
FAILED: CMakeFiles/sdbus-c++-objlib.dir/src/Proxy.cpp.o
/usr/bin/clang++  -DBUILD_LIB=1 -DLIBSYSTEMD_VERSION=243 -I/home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sdbus-cpp/include -I/home/ci/src/cesnet-gerrit-czechlight/CzechLight/dependencies/sdbus-cpp/src …
```
=> Fix build with clang 9.0.1 and libcxx

src/Proxy.cpp
This fixes a data race that could potentially occur: a spurious wakeup after mutex unlock but before notify would result in notify called on a destroyed condition variable object. Hence, the notification must occur under the locked mutex to achieve precise scheduling of events.
Fixes #108
=> Fix potential data race in Proxy's condition variable

include/sdbus-c++/Types.h
sdbus::ObjectPath and sdbus::Signature copy constructors are implicitly
declared as deleted when compiling with Linaro's ARM toolchain [1] gcc8.3.
Explicitly listing the copy constructors for affected classes fixes the problem.
[1] https://www.linaro.org/
Here is the failure (for simplified code)
```cpp
const sdbus::ObjectPath foo("/path/to/somewhere");
const sdbus::ObjectPath bar(foo);
```
```  
/cesnet/build-clearfog/build/velia-custom/src/inputs/DbusSystemdInput.cpp: In member function ‘void velia::DbusSystemdInput::registerSystemdUnit(sdbus::IConnection&, const string&, const sdbus::ObjectPath&)’:
/cesnet/build-clearfog/build/velia-custom/src/inputs/DbusSystemdInput.cpp:77:36: error: use of deleted function ‘sdbus::ObjectPath::ObjectPath(const sdbus::ObjectPath&)’
const …
```
=> Fix build with gcc8.3

.github/workflows/ci.yml, README.md, cmake/LibsystemdExternalProject.cmake
This introduces GitHub CI which runs builds and tests in a matrix configuration. It also changes the systemd repo to stable one. And puts the CI badge (plus a few more badges) to the README page.
Fixes #44
=> Introduce CI workflow based on GitHub Actions

tools/CMakeLists.txt
I was working on a conan.io package for sdbus-c++ and I had a problem to build it with `-DBUILD_CODE_GEN=ON` option, because it couldn't find EXPAT headers.
This patch is required if EXPAT library is installed in non-standard location.
Without `target_include_directories` cmake will find EXPAT library:
```
-- Found EXPAT: .../lib/libexpat.a (found version "2.2.10")
```
But `xml.cpp` compilation will fail with error:
```
tools/xml2cpp-codegen/xml.cpp:7:10: fatal error: expat.h: No such file or directory
7 | #include <expat.h>
```
=> xml2cpp: Add missing EXPAT include dirs

CMakeLists.txt
```
~/package $ pkg-config --modversion libsystemd
243.4
~/package $
```
Split it to the list and use the first one
Refer to https://bugzilla.redhat.com/show_bug.cgi?id=1862714
=> Fixes for floating point systemd version such as  243.4

include/sdbus-c++/Types.h
Explicitly list default copy assignment operator otherwise it is deleted in gcc 8.3.
=> fix: missing copy assignment operator in gcc 8.3

cmake/LibsystemdExternalProject.cmake
The ninja generator requires the BUILD_BYPRODUCTS specifier to work out
the dependencies.
This fixes issue #73 which was closed as a cmake bug.
=> cmake: fix building with BUILD_LIBSYSTEMD and ninja generator.

CMakeLists.txt
Building on SUSE fails, as std::thread usage requires linking
against pthread:
```
/usr/bin/c++ -fPIC -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -DNDEBUG -O3 -DNDEBUG -flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libsdbus-c++.so.0 -o libsdbus-c++.so.0.8.3 CMakeFiles/sdbus-c++-objlib.dir/src/Connection.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/Error.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/Message.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/Object.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/Proxy.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/Types.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/Flags.cpp.o CMakeFiles/sdbus-c++-objlib.dir/src/VTableUtils.c.o …
```
=> Find and link against pthread

ChangeLog, src/Connection.cpp, src/Connection.h, src/IConnection.h, src/Proxy.cpp, tests/integrationtests/DBusSignalsTests.cpp, tests/integrationtests/files/org.sdbuscpp.integrationtests.conf
fix for #145 
A new integration test is added first with uncovers the issue. It shows that a proxy gets the signal from any/all bus names (destinations) if the object path and interface match. We want the proxy to only connect to the `destination` which was given as argument during construction.
A missing `sender=..` in the match filter rule solves the issue.
=> fix #145, signals are not filtered by sender

docs/using-sdbus-c++.md, tools/CMakeLists.txt, tools/cmake/sdbus-c++-tools-config.cmake.in, tools/pkgconfig/sdbus-c++-tools.pc.in
When a project uses automatically generated interface headers using the stub generator it is convenient if the conversion by the stub generator can be integrated into the project itself. Until now it was not possible to search for the availibility of the stub generator and it had to be invoked blindly.
This commit provides CMake and PkgConfig files which allow projects to check availibility of the stub generator as well as its version and to automatically resolve its installation path.
=> Provide CMake config and PkgConfig files for tools

README.md, docs/using-sdbus-c++.md, tests/integrationtests/DBusConnectionTests.cpp, tests/integrationtests/DBusGeneralTests.cpp
This PR:
* removes unnecessary `releaseName()` calls in integration tests,
* adds a custom gtest message if a connection test fails, pointing the user to the potential cause of the issue,
* adds more documentation on how to test sdbus-c++ build.
Fixes #162 
Fixes #155
=> fix: minor documentation and test improvements

docs/CMakeLists.txt, docs/Doxyfile.in, docs/using-sdbus-c++.md
Here's a couple small changes to enhance the project's current doxydocs.
I've added "{#mainpage}" to the "using-sdbus-c++" file to tell doxygen to use that as the mainpage for the documentation.  
I also had to add a custom rule that copies the png into the html directory.  This is to work around a bug in doxygen related to images inside of markdown text. 
And of course the Doxyfile.in needed to have the using-sdbus-c++ included.
=> Add README and sdbus-c++ tutorial as additional pages in doxydocs

include/sdbus-c++/Message.h, src/Message.cpp
With this patch it is possible to create unicast signals - e.g. I want to keep client informed about the progress in processing of his request using regularly sent dbus signals so that the client could print a progress bar or something. Only the client that sent original request is interested in such signal:
```
auto signal = dbus_object->createSignal(interface, "ProcessProgress");
signal.setDestination(request_sender);
signal << items_processed;
signal << items_total;
dbus_object->emitSignal(signal);
```
=> Add API to set signal destination

include/sdbus-c++/IProxy.h, src/Proxy.cpp, src/Proxy.h
This provides access to the proxy's bus connection so code using the proxy does not need to store an external reference to it.
A matching function is already available in `IObject`.
I mentioned this change here: https://github.com/Kistler-Group/sdbus-cpp/discussions/169
=> Add IProxy::getConnection()

include/sdbus-c++/IProxy.h, tests/integrationtests/DBusAsyncMethodsTests.cpp
This is helpful in use cases where a user defined class wants to store a `PendingAsyncCall` as a member variable, or in a STL container.
I mentioned this change here: https://github.com/Kistler-Group/sdbus-cpp/discussions/169
=> Enable default construction of PendingAsyncCall

src/Proxy.cpp, src/Proxy.h
replaces #134 
fixes #133
@ChristianS99 's observations about the race condition while destructing a proxy were extremely helpful. As it was mentioned, #134 didn't solve all issues in an elegant way. So this PR should replace it.
[interfaces_](https://github.com/Kistler-Group/sdbus-cpp/blob/master/src/Proxy.h#L105) is the critical resource which is potentially shared by the main thread and connection loop thread.
The first approach was to wrap all access to `interfaces_` into it's own thread-safe class, similar to [class AsyncCalls](https://github.com/Kistler-Group/sdbus-cpp/blob/master/src/Proxy.h#L111). But this solution was complex and didn't fully solve the [ABA problem](https://en.wikipedia.org/wiki/ABA_problem) which @ChristianS99 described.
So the solution in this PR is to just …
=> Issue 133 race in proxy destruct 

src/Message.cpp, tests/unittests/Message_test.cpp
* Add missing nullptr check in Message::peekType().
* According to its specification, sd_bus_message_peek_type() sets a
given contents parameter to NULL if the next element in a message is
not a container. Since assigning a nullptr to a std::string has
undefined behaviour (typically resulting in an invalid memory access),
Message::peekType() must not assign contentsSig unconditionally.
=> Fix issue #135: Segfault in Message::peekType()

docs/using-sdbus-c++.md
I'm not sure but it may be helpful to have reference to Conan package of sdbus-c++ in documentation.
=> docs: Add information about conan recipe

include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Connection.h, src/ISdBus.h, src/SdBus.cpp, src/SdBus.h, tests/unittests/Connection_test.cpp, tests/unittests/mocks/SdBusMock.h
This internally calls `sd_bus_open()`, which automatically selects the system or session bus connection based on the presence and content of a `DBUS_STARTER_BUS_TYPE` environment variable and whether the calling process has root privileges.
This option is very helpful when creating services and clients that will use the system bus in production, but connect to a session for testing.
Note: it was desirable to change `createConnection()` to open the default bus instead of creating a new function, but I assumed this would be too controversial, as it could break existing code that relies on it always opening the system bus.
**Additional changes**
* Removed assertions null-checking `make_unique()` return values. `make_unique()` calls `new`, and `new` is expected to throw or abort on failure, …
=> Add createDefaultBusConnection()

include/sdbus-c++/ConvenienceApiClasses.inl, src/Object.cpp, src/Proxy.cpp
This simply assures that `sdbus::Error` exceptions don't bubble from `Proxy` callbacks up to the libsystemd, which is a C library, and this may be unsafe. The only situation that I could think of that this may have happened until now was:
* Clients themselves did not catch these exceptions from their sdbus-c++ calls in their callback handlers, and these calls threw;
* Or, deserialization of arguments in e.g. a signal handler failed (because of signature mismatch, for example).
These situations shall not put down the entire event loop to its knees, hence they are caught just for sure and ignored.
Fixes https://github.com/Kistler-Group/sdbus-cpp/issues/178
=> Catch sdbus-c++ exceptions flying from Proxy callbacks to libsystemd

docs/using-sdbus-c++.md, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/TypeTraits.h
Currently, signal handlers are not invoked (i.e., the signal is silently dropped) if there is a signal signature mismatch. This PR enables clients to be informed of such situations (e.g. they make a mistake in signal's signature). So with this, if clients want to be informed of such situations, they can prepend `const sdbus::Error*` parameter to their signal handler's parameter list. This argument will be `nullptr` in normal cases, and will provide access to the corresponding `sdbus::Error` exception in case of deserialization failures
=> Support Error parameter in signal handlers

tests/googletest-download/CMakeLists.txt.in
Upstream googletest deleted the master branch in favor of main.﻿
=> googletest-download: replace master with main

docs/using-sdbus-c++.md
That method has its name almost two years by now. Time to show it some respect ;)
https://github.com/Kistler-Group/sdbus-cpp/blob/dc0f487751690999aaa61e507bbd16bdf111949d/include/sdbus-c%2B%2B/MethodResult.h#L61
=> fix method name in example

docs/using-sdbus-c++.md, tools/xml2cpp-codegen/ProxyGenerator.cpp
Allow to use human readable [chrono literals][1] to specify method call
timeout. The change is backward compatbile - if no unit is provided,
the fallback is "us".
Example:
```xml
<annotation name="org.freedesktop.DBus.Method.Timeout" value="500ms"/>
```
[1]: https://en.cppreference.com/w/cpp/symbol_index/chrono_literals
=> codegen: Support chrono literal timeout by ProxyGenerator

include/sdbus-c++/ConvenienceApiClasses.h, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/IProxy.h, src/Proxy.cpp, src/Proxy.h, tests/integrationtests/DBusSignalsTests.cpp, tests/integrationtests/integrationtests-proxy.h
Summary:
I implemented your second approach as follows:
- Add `void IProxy::unregisterSignalHandler(const std::string& interfaceName, const std::string& signalName)` method.
- Add new auxiliary class `SignalUnsubscriber`.
- Add `SignalUnsubscriber IProxy::muteSignal(const std::string& signalName)` method.
- Extend **integrationtests/DBusSignalsTests** by adding 4 testcases for unregistring signal's handler.
=> Fix #214: Add means to unregister signal handler

src/Proxy.cpp, tests/integrationtests/DBusSignalsTests.cpp
Fixes [comment](https://github.com/Kistler-Group/sdbus-cpp/pull/223/files#r768955213)
/cc @dleeds-cpi
=> fix: use non-mutating find in signal unregistration

include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Message.cpp, src/Proxy.cpp
This is a kind of little follow-up to #91 and contains:
* removal of `notifyEventLoopNewTimeout` call from synchronously sent messages,
* using `activeTimeout_` in a more relaxed way, without heavy ordering constraints,
* a little code reformatting and re-organization, mostly for consistency.
=> fix: minor fixes for async timeout handling

include/sdbus-c++/Types.h, tests/unittests/Types_test.cpp
* Since ObjectPath and Signature have a user-declared copy-ctor and copy
assignment operator the implicit declaration of corresponding move
operations is disabled. Explicitly add defaulted versions so that
move operations actually move instead of copy.
* See: https://github.com/Kistler-Group/sdbus-cpp/issues/230
=> Issue #230: Enable move for ObjectPath and Signature.

tests/CMakeLists.txt, tests/integrationtests/Defs.h
Fixes #234 
@lubo-svk @Oxymoron79
=> fix(tests): printer for std::chrono in googletest v1.11.0

src/Connection.cpp, src/Connection.h
Value of `0` is a valid file descriptor. It is usually assigned to standard input, but in services which close stadard I/O file descriptors, it can be reused. If it does get reused in EventFd, the code causes the service to abort despite everything being ok. The assert is somewhat superfluous as the file descriptor is always valid. If we fail to initialise it in the constructor, we throw. Even if we would survived the failed constructor (we don't), the value would have been undefined, so the usefulness of the assert is close to none. But well..., let's keep it, and have the file descriptor default initialised to an invalid value.
=> Fix invalid assert

docs/using-sdbus-c++.md
sdbus-c++ package was added to Buildroot in the recent stable release (2022.02).
=> docs: Add information about Buildroot package

docs/using-sdbus-c++.md, include/sdbus-c++/IConnection.h, include/sdbus-c++/TypeTraits.h, src/Connection.cpp, src/Connection.h, src/Proxy.cpp, tests/integrationtests/DBusGeneralTests.cpp
This implements support for synchronous installation of D-Bus match rules. See [D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html) for more info on match rules.
=> feat: add support for match rules

include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Connection.h, src/ISdBus.h, src/SdBus.cpp, src/SdBus.h, tests/unittests/Connection_test.cpp, tests/unittests/mocks/SdBusMock.h
The new function helper `createSessionBusConnectionWithAddress` allows
to create connection to session bus with custom address.
Signed-off-by: Alexander Livenets <a.livenets@gmail.com>
=> feat: add support for session bus connection at custom address

src/Connection.cpp, src/Connection.h, src/IConnection.h, src/ISdBus.h, src/Message.cpp, src/SdBus.cpp, src/SdBus.h, tests/unittests/Connection_test.cpp, tests/unittests/mocks/SdBusMock.h
This fixes #277 and addresses @dleeds-cpi's proposal that is part of discussion #169.
To create a plain D-Bus messages (used to implement the concept of `Variant`s, for example), we need a D-Bus connection. However, with current sd-bus API and its implementation, it's possible to optimize and create a "pseudo" connection which does not really connect to and thus does not need D-Bus daemon, yet remains in a state that is sufficient to create local D-Bus messages and work with them.
This is a bit of a hack, but
* it enables us and our clients to write unit tests around plain messages and `Variant`s that fulfill FIRST principles, and are independent from presence of D-Bus daemon.
* leads to faster and more light-weight code when creating plain D-Bus messages/`Variant`s.
@dleeds-cpi would you …
=> refactor: use pseudo D-Bus connection for plain messages

CMakeLists.txt, pkgconfig/sdbus-c++.pc.in
This works whether `BUILD_LIBSYSTEMD` is `ON` or the separate build of libsystemd picked up by pkg-config is static. The Gentoo Linux package requires the latter.
=> Don't include libsystemd as pkg-config dependency when statically linked

docs/using-sdbus-c++.md, include/sdbus-c++/IProxy.h, include/sdbus-c++/ProxyInterfaces.h, src/Proxy.cpp, src/Proxy.h, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/TestProxy.cpp, tests/integrationtests/TestProxy.h
This adds a possibility to create a proxy which has its own D-Bus connection to a bus, but which doesn't run an event loop thread for it internally. Such proxies are "light-weight", meant to be created, used (for some classic D-Bus calls), and discarded.
=> feat: add support for proxy with no event loop thread

docs/using-sdbus-c++.md, include/sdbus-c++/AdaptorInterfaces.h, include/sdbus-c++/ProxyInterfaces.h, tests/integrationtests/integrationtests-adaptor.h, tests/integrationtests/integrationtests-proxy.h, tests/perftests/perftests-adaptor.h, tests/perftests/perftests-proxy.h, tests/stresstests/celsius-thermometer-adaptor.h, tests/stresstests/celsius-thermometer-proxy.h, tests/stresstests/concatenator-adaptor.h, tests/stresstests/concatenator-proxy.h, tests/stresstests/fahrenheit-thermometer-adaptor.h, tests/stresstests/fahrenheit-thermometer-proxy.h, tools/xml2cpp-codegen/AdaptorGenerator.cpp, tools/xml2cpp-codegen/ProxyGenerator.cpp
Generated adaptor and proxy classes did (accidentally) not support move semantics, since they have explicitly defaulted constructor, which prohibited the compiler from providing move operations automatically. Now the implementation of these classes adheres to the Rule of Five (Rule of All or Nothing). Move semantics is enabled, copy semantics disabled. This allows these classes to be used in containers, in `std::variant`, etc.
=> refactor: support move semantics in generated adaptor and proxy classes

docs/Doxyfile.in, include/sdbus-c++/IConnection.h, include/sdbus-c++/IProxy.h, include/sdbus-c++/ProxyInterfaces.h
=> docs: strip absolute paths from doxygen documentation

.github/workflows/ci.yml, CMakeLists.txt, ChangeLog, docs/using-sdbus-c++.md, include/sdbus-c++/IConnection.h, include/sdbus-c++/IProxy.h, include/sdbus-c++/Message.h, src/Connection.cpp, src/Connection.h, src/IConnection.h, src/ISdBus.h, src/Message.cpp, src/MessageUtils.h, src/Proxy.cpp, src/Proxy.h, src/SdBus.cpp, src/SdBus.h, src/Utils.h, tests/CMakeLists.txt, tests/integrationtests/DBusConnectionTests.cpp, tests/integrationtests/TestProxy.cpp, tests/integrationtests/TestProxy.h, tests/unittests/PollData_test.cpp, tests/unittests/mocks/SdBusMock.h
This is the first one in the planned series of PR's with features/refactorings/fixes requiring breaking changes in API/ABI/behavior, leading to new sdbus-c++ v2. A new feature branch `release/v2.0` has been created for accumulating these PRs before it's merged to master.
Changes in this MR are conceptually a re-design of various areas with the focus on async D-Bus connection handling. There are simplifications, fixes for async handling (finally #88 is solved properly and completely, issue with thread id is fixed in #141) and external event loop integration. And this PR is a necessary pre-requisite the upcoming PR with sd-event integration.
Fixes #88 #141 
List of changes (see ChangeLog for more detailed listing):
* In *synchronous* D-Bus calls, the proxy now **always** blocks the …
=> refactor: simplify async D-Bus connection handling

docs/using-sdbus-c++.md, include/sdbus-c++/ConvenienceApiClasses.h, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/IProxy.h, include/sdbus-c++/TypeTraits.h, src/Proxy.cpp, src/Proxy.h, tests/integrationtests/DBusAsyncMethodsTests.cpp, tests/integrationtests/TestProxy.cpp, tests/integrationtests/TestProxy.h
In addition to the existing callback-based asynchronous D-Bus method calls, for more convenience, sdbus-c++ API is now extended to also support `std::future`-based async method calls.
=> feat: add support for std::future-based async calls

src/Proxy.cpp, src/Proxy.h
After calling message.send it is possible for the callback to be called before callData is added to pendingAsyncCalls_. This results in callData being added there after the callback is called and never being removed.
Signed-off-by: Anthony Brandon <anthony@amarulasolutions.com>
=> Fix race condition in Proxy::callMethod.

docs/using-sdbus-c++.md, include/sdbus-c++/IConnection.h, src/Connection.cpp, src/Connection.h, tests/CMakeLists.txt, tests/integrationtests/DBusAsyncMethodsTests.cpp, tests/integrationtests/DBusGeneralTests.cpp, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/DBusPropertiesTests.cpp, tests/integrationtests/DBusSignalsTests.cpp, tests/integrationtests/DBusStandardInterfacesTests.cpp, tests/integrationtests/TestFixture.cpp, tests/integrationtests/TestFixture.h
This implements integration of `sd-event` event loop.
Integration tests are duplicated to run on both internal event loop as well as an external, sd-event-based event loop.
Closes #271
=> feat: introduce sd-event integration

CMakeLists.txt, src/Connection.cpp, tools/CMakeLists.txt
I accidentally closed the other issue by wrongly deleting my branch... github is somewhat picky about that...
Fixes #324
Continues #325
=> Prevent installing a time event, when there's no need for a timeout (cont.)

.github/workflows/ci.yml
Ubuntu 18.04 seems to be no longer supported by GitHub CI.
=> chore(ci): remove ubuntu-18.04 container image

src/Message.cpp
In standard cases, we could do with simply function-local static pseudo connection instance in `createPlainMessage()` used to implement `Variant` concept. However, it may happen that client's sdbus-c++ objects outlive this static connection instance (because they are used in global application objects that were created before this connection, and thus are destroyed later).
This by itself sounds like a smell in client's application design, but it is downright stinky in sdbus-c++ because it has no control over when client's dependent statics get destroyed. A "Phoenix" pattern (see [Modern C++ Design - Generic Programming and Design Patterns Applied](https://www.amazon.com/Modern-Design-Programming-Patterns-Depth-ebook/dp/B00AU3JUHG), by Andrei Alexandrescu) is applied to fix this by …
=> fix: pseudo-connection static lifetime issue

include/sdbus-c++/MethodResult.h
when compiling with -Wall, compiler (at least gcc and clang) complains, that statement has no effect, when the parameter list is empty. When adding a void cast, this warning is silenced. In case of empty parameter list, it actually is intended, that this statement doesn't do anything.
Maybe this shouldn't be a compiler warning at all, IDK, but maybe there are situations, where this warning is appropriate even for an empty list.
(I guess (void) in https://github.com/Kistler-Group/sdbus-cpp/blob/c39bc637b8df7791c697c7e75f1376ac0a9b9678/include/sdbus-c%2B%2B/TypeTraits.h#L527 serves the same purpose)
=> fix: add cast to void to silence compiler warning in case of empty parameter list

docs/using-sdbus-c++.md, include/sdbus-c++/Message.h, include/sdbus-c++/TypeTraits.h, src/Message.cpp, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/TestAdaptor.cpp, tests/integrationtests/TestAdaptor.h, tests/integrationtests/integrationtests-adaptor.h, tests/integrationtests/integrationtests-proxy.h, tests/integrationtests/org.sdbuscpp.integrationtests.xml, tests/unittests/Message_test.cpp, tests/unittests/TypeTraits_test.cpp
Add support for `std::array`, `std::span` and `std::unordered_map` in D-Bus message serialization/deserialization API.
TBD: Extending codegen XML to allow clients to choose from STL containers to use in C++ bindings?
=> feat: support serialization of array, span and unordered_map

include/sdbus-c++/Message.h, include/sdbus-c++/Types.h, src/Message.cpp, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/DBusSignalsTests.cpp, tests/integrationtests/DBusStandardInterfacesTests.cpp, tests/integrationtests/TestAdaptor.cpp, tests/stresstests/sdbus-c++-stress-tests.cpp
* `Message::appendArray` and `Message::readArray` are made public so they can be used by clients for their custom array representations
* `Variant` converting constructor is made explicit, to exclude it from candidate list when compiler looks for insertion/extraction operators for custom client types
This is a follow-up to #346 and #347
=> refactor: improve type extensibility and its safety

CMakeLists.txt, pkgconfig/sdbus-c++.pc.in
* CMakeLists.txt: Fallback to elogind when libsystemd could not be found.
=> build: Add support for elogind.

docs/using-sdbus-c++.md, tests/integrationtests/TestProxy.cpp, tools/xml2cpp-codegen/AdaptorGenerator.cpp, tools/xml2cpp-codegen/ProxyGenerator.cpp
Some time ago, in #311, support for `std::future`-based async calls was introduced on basic as well as convenience API level. Now, the support is also introduced on the generated code level.
Closes https://github.com/Kistler-Group/sdbus-cpp/discussions/317
=> feat: support std::future-based async methods in codegen tool

tests/integrationtests/DBusMethodsTests.cpp
- glibc, bionic expand `ETIMEDOUT` to `Connection timed out`
- BSD libc and [musl >= 0.9.10](https://git.musl-libc.org/cgit/musl/commit/?id=d75348ddda4e) expand `ETIMEDOUT` to `Operation timed out`
- POSIX [1997](https://pubs.opengroup.org/onlinepubs/7908799/xsh/errors.html) and [2018](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html) support both `Connection timed out` and `Operation timed out`
- According to [unix-history-repo](https://github.com/dspinellis/unix-history-repo) `ETIMEDOUT` appeared in BSD 4.1c (1982) as `Connection timed out` but with 4.4-Lite1 (1994) changed to `Operation timed out`
=> chore(tests): unbreak release/v2.0 on FreeBSD

src/Proxy.cpp, src/Proxy.h
This bug was introduced by c39bc637b8df7791 and can be reproduced by configuring with
cmake -S . -B build -DBUILD_TESTS=yes -DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_CXX_FLAGS="-Wno-error=deprecated-copy -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope"
and running `cmake --buid build && cmake --build build -t test` or `build/tests/sdbus-c++-integration-tests --gtest_filter=SdbusTestObject.HandlesCorrectlyABulkOfParallelServerSideAsyncMethods`
The issue is that `sdbus_async_reply_handler` can call `removeCall`, which writes to `data->finished`, but `data` can point to the stack of `sendMethodCallMessageAndWaitForReply`, which can return as soon as `asyncCallData->callback` is called.
As a fix, I restored some of the logic removed in c39bc637b8df7791. …
=> fix: Use-after-return in synchronous calls

include/sdbus-c++/IConnection.h, include/sdbus-c++/IObject.h, include/sdbus-c++/IProxy.h, include/sdbus-c++/Message.h, src/Connection.cpp, src/Connection.h, src/ISdBus.h, src/Object.cpp, src/Object.h, src/Proxy.cpp, src/Proxy.h, src/SdBus.cpp, src/SdBus.h, tests/integrationtests/TestAdaptor.cpp, tests/integrationtests/TestAdaptor.h, tests/integrationtests/TestProxy.cpp, tests/integrationtests/TestProxy.h, tests/unittests/mocks/SdBusMock.h
This is a little simplification of sdbus-c++, because sd-bus also keeps the currently processed message, and provides an API to retrieve it, so we just use this API instead of keeping processed message also on our level.
Follow-up: refactor message callback handlers to take input messages by value.
=> refactor: use sd-bus API to get current message

ChangeLog, docs/using-sdbus-c++.md, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/IConnection.h, include/sdbus-c++/TypeTraits.h, src/Connection.cpp, src/Object.cpp, src/Proxy.cpp, src/Proxy.h, tests/integrationtests/DBusGeneralTests.cpp
Signatures of callbacks `async_reply_handler`, `signal_handler`, `message_handler` and `property_set_callback` were modified to take input message objects by value, as opposed to non-const ref.
Callee assumes ownership of the message. This API is more idiomatic, more expressive, cleaner and safer. Move semantics is used to pass messages to the callback handlers. In some cases, this also improves performance.
=> refactor: let callbacks take message objects by value

src/Proxy.cpp, src/Proxy.h
Since synchronous D-Bus calls are simplified in v2.0 and no more implemented in terms of an async call, the issue reported in #362 is no more relevant, and we can return to the simple boolean flag for indicating a finished call.
=> refactor: simplify async call state flag

tests/integrationtests/DBusMethodsTests.cpp
The test now works with Clang, libc++ and `-O2` optimization, since the underlying implementation has been completely re-designed and doesn't suffer from that problem anymore.
=> fix(tests): enable skipped test for Clang and FreeBSD

ChangeLog, include/sdbus-c++/Types.h, tests/integrationtests/DBusSignalsTests.cpp
This makes the library more robust and prone to user's errors when the user writes an extension for their custom type. In case they forget to implement a serialization function for that type and yet insert an object of that type into `sdbus::Message`, the current behavior is that, surprisingly, the library masks the error as it resolves the call to the `Variant` overload, because `Variant` provides an implicit template converting constructor, so the library tries to construct first the Variant object from the object of custom type, and then inserting into the message that `Variant` object. `Variant` constructor serializes the underlying object into its internal message object, which resolves to the same message insertion overload, creating an infinite recursion and ultimately the stack …
=> refactor: make Variant constructor explicit

docs/using-sdbus-c++.md, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/Error.h, src/Object.cpp, src/Proxy.cpp, src/Utils.h
* Catch and process all exceptions (not just `sdbus::Error`) from callback handlers
* Unify handling of exceptions from all types of callbacks -- always set `sd_bus_error` and return a negative result number in case of exception
Although `libsystemd` logs (with `DEBUG` severity) all errors from such callback handlers (except method callback handler), it seems to be out of our control. One of handy sdbus-c++ features could be the ability for clients to install a log callback, which sdbus-c++ would call in case of exceptions flying from callback handlers. In case something doesn't work for clients (especially novices), they can first look into these logs.
This may be handy in common situations like ignored signals on client side because of the inadvertent mismatch between real signal …
=> refactor: improve handling of exceptions from callback handlers

include/sdbus-c++/Message.h
* https://gcc.gnu.org/gcc-14/porting_to.html
Couldn't discern patterns header includes other than newer additions being bottom from git-blame, so I followed the apparent precedent.
https://bugs.gentoo.org/917157
=> fix: Add header for gcc-14 that isn't included by default anymore

.github/workflows/ci.yml, CMakeLists.txt, README.md, tests/CMakeLists.txt
* Change default test installation path to `tests/sdbus-c++` , while also respecting `CMAKE_INSTALL_PREFIX`
* Introduce `INSTALL_TESTS` CMake option, so `BUILD_TESTS` is now split into `BUILD_TESTS` just for building and `INSTALL_TESTS` for installing the test binaries
Per discussion in https://github.com/Kistler-Group/sdbus-cpp/pull/358#discussion_r1327946080, the change in the default settings is fine a for a minor release.
Fixes #381
=> chore: add INSTALL_TESTS CMake option

src/Connection.cpp
This is a follow-up to #375. It covers match callback handlers that were missed in #375.
=> refactor: handle exceptions correctly also in match callback handlers

include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/IProxy.h, src/Proxy.cpp, src/Proxy.h, tests/integrationtests/TestProxy.cpp
This makes naming consistent, so all asynchronously working functions have `Async` suffix.
Replaces #393
=> refactor: add Async suffix to async callMethod functions

docs/using-sdbus-c++.md, include/sdbus-c++/ConvenienceApiClasses.inl, include/sdbus-c++/IProxy.h, include/sdbus-c++/TypeTraits.h, src/Proxy.cpp, tests/integrationtests/DBusAsyncMethodsTests.cpp, tests/integrationtests/DBusStandardInterfacesTests.cpp, tests/integrationtests/TestProxy.cpp, tests/integrationtests/TestProxy.h, tests/stresstests/concatenator-proxy.h, tests/stresstests/sdbus-c++-stress-tests.cpp, tools/xml2cpp-codegen/ProxyGenerator.cpp
This switches from a raw pointer to `std::optional` type to pass prospective call errors to the client (using `std::optional` was not possible years back when sdbus-c++ was based on C++14). This makes the API a little clearer, safer, idiomatically more expressive, and removes potential confusion associated with raw pointers (like ownership, lifetime questions, etc.). However, this is a *breaking* API change (for async users). The upcoming v2 release is a nice candidate to accommodate such a change.
@dleeds-cpi What are your thoughts about it?
=> refactor: use optional for passing potential call errors

.github/workflows/ci.yml, CMakeLists.txt, README.md, cmake/LibsystemdExternalProject.cmake, docs/CMakeLists.txt, docs/using-sdbus-c++.md, examples/CMakeLists.txt, tests/CMakeLists.txt, tools/CMakeLists.txt
This improves usability of sdbus-c++ in downstream CMake projects. CMake options now have `SDBUSCPP_` prefix so potential conflicts with downstream options/variables are minimized. Also, all configurable options and variables are placed in a single place in root CMake file.
=> refactor: rename and re-organize CMake options

CMakeLists.txt, docs/CMakeLists.txt, examples/CMakeLists.txt, tests/CMakeLists.txt, tools/CMakeLists.txt
This, too, is a change for better scoping and usability in downstream CMake projects
=> chore: rename COMPONENTs in CMake

ChangeLog, docs/using-sdbus-c++.md, include/sdbus-c++/IConnection.h, src/Connection.cpp, src/IConnection.h, src/Proxy.cpp, tests/integrationtests/DBusConnectionTests.cpp, tests/integrationtests/DBusGeneralTests.cpp, tests/integrationtests/DBusSignalsTests.cpp
This PR makes things around connection factories a little more consistent and more intuitive:
* `createConnection()` has been removed. One shall call more expressive `createSystemConnection()` instead to get a connection to the system bus.
* `createDefaultBusConnection()` has been renamed to `createBusConnection()`, so as not to be confused with libsystemd's `default_bus`, which is a different thing (a reusable thread-local bus).
`Proxy`ies still by default call `createBusConnection()` to get a connection when the connection is not provided explicitly by the caller, but now `createBusConnection()` does a different thing, so now the `Proxy`ies connect to either session bus or system bus depending on the context (as opposed to always to system bus like before).
=> refactor: rename connection creation methods

CMakeLists.txt, ChangeLog, README.md, docs/using-sdbus-c++.md, tests/CMakeLists.txt
A new CMake configuration variable `SDBUSCPP_SDBUS_LIB` has been introduced that enables clients to specify which sd-bus implementation library shall be used by sdbus-c++.
Fixes #399
=> chore(cmake): implement more flexible searching for sd-bus libs

include/sdbus-c++/Message.h, include/sdbus-c++/TypeTraits.h, tests/CMakeLists.txt, tests/unittests/Message_test.cpp, tests/unittests/TypeTraits_test.cpp
This PR adds the possiblity for C++20 compilers to use enums, enum classes and enum structs.
C++20 is required because of `requires`. I coulndn't find a way without it. If you're more successful than me, please open a PR or edit this PR, feel free :)
If anything bugs you, please comment
=> feat: support enums in D-Bus serialization and signatures

src/ScopeGuard.h
`std::uncaught_exception()` is declared in `<exception>`.
=> Add missing #include <exception>

docs/using-sdbus-c++.md, include/sdbus-c++/Message.h, include/sdbus-c++/TypeTraits.h, tests/unittests/Message_test.cpp, tests/unittests/TypeTraits_test.cpp
It can be useful to directly serialize from and deserialize to `std::variant<>` instead of `sdbus::Variant`.
=> Support serialization and deserialization of std::variant

include/sdbus-c++/TypeTraits.h, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/TestAdaptor.cpp, tests/integrationtests/TestAdaptor.h, tests/integrationtests/integrationtests-adaptor.h, tests/integrationtests/integrationtests-proxy.h
Also use `always_false` technique instead of `sizeof` trick for unsupported D-Bus type representation static assert. This one is more expressive and leads to more specific, more revealing compiler error messages.
=> test: add integration tests for std::variant

docs/using-sdbus-c++.md, examples/org.freedesktop.DBus.ObjectManager/examplemanager-planet1-client-glue.h, include/sdbus-c++/Types.h, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/integrationtests-proxy.h
This:
* is a good practice according to the C++ core guidelines, as it makes the code safer and better follows the principle of least astonishment
* is consistent with the standard library style, where wrappers like `std::variant`, `std::any`, `std::optional`... also do not provide an implicit conversion to the underlying type
* paves the way for the upcoming `std::variant` <-> `sdbus::Variant` implicit conversions without surprising behavior in some edge cases
=> fix: make Variant conversion operator explicit

.github/workflows/ci.yml, docs/using-sdbus-c++.md, include/sdbus-c++/Message.h, include/sdbus-c++/TypeTraits.h, include/sdbus-c++/Types.h, include/sdbus-c++/VTableItems.inl, src/Message.cpp, tests/unittests/Message_test.cpp, tests/unittests/TypeTraits_test.cpp
Since sdbus-c++ knows types of D-Bus call/signal/property input/output parameters at compile time, why not assemble the D-Bus signature strings at compile time, too, instead of assembling them at run time as `std::string` with likely cost of (unnecessary) heap allocations...
`std::array` is well supported `constexpr` type in C++20, so we harness it to build the D-Bus signature string and store it into the binary at compile time.
=> refactor: enable compile-time D-Bus signature generation

ChangeLog, docs/using-sdbus-c++.md, include/sdbus-c++/IConnection.h, include/sdbus-c++/IObject.h, src/Connection.cpp, src/Connection.h, src/IConnection.h, src/Object.cpp, src/Object.h
This makes the signature of `addObjectManager()` function overloads consistent with common API design of the library.
=> refactor: object manager API

docs/using-sdbus-c++.md, include/sdbus-c++/IConnection.h, include/sdbus-c++/Message.h, src/Connection.cpp, src/Connection.h, src/IConnection.h, src/Message.cpp, src/Object.cpp, src/Proxy.cpp, tests/integrationtests/DBusGeneralTests.cpp
Make all the API consistent by using `return_slot_t`-based overloads for returning the slots to clients, and overloads without that tag for "floating" slots. `floating_slot_t` tag was previously added for API backwards compatibility reasons, but now is a (counter-)duplicate to the `return_slot_t`.
=> refactor: remove floating_slot_t tag and use return_slot_t instead

.github/workflows/ci.yml, ChangeLog, docs/using-sdbus-c++.md, include/sdbus-c++/Types.h, tests/unittests/Message_test.cpp
This introduces `SDBUSCPP_REGISTER_STRUCT()` macro that helps clients conveniently, in one line, teach sdbus-c++ to recognize and accept their custom C++ struct types wherever D-Bus structs are expected in a D-Bus API.
The macro saves some boilerplate that would otherwise be needed on client side for every registered struct.
=> feat: add macro to teach sdbus-c++ about user-defined structs

include/sdbus-c++/TypeTraits.h, tests/unittests/Message_test.cpp, tests/unittests/TypeTraits_test.cpp
This fixes the template specialization ambiguity error when a `signature_of` applied upon a `const` (and/or `volatile`) enum type would render the `const` specialization and the enum specialization as two equally-ranked candidates.
Fixes #443
=> fix: const enum signature_of ambiguity error

include/sdbus-c++/Message.h, src/MessageUtils.h
Library clients may need to manually create plain sdbus-c++ message to be able to unit test their code.
Fixes #277
=> refactor: make createPlainMessage public

include/sdbus-c++/IObject.h, include/sdbus-c++/IProxy.h, include/sdbus-c++/Message.h, src/Connection.cpp, src/Connection.h, src/IConnection.h, src/ISdBus.h, src/Message.cpp, src/MessageUtils.h, src/Object.cpp, src/Object.h, src/Proxy.cpp, src/Proxy.h, src/SdBus.cpp, src/SdBus.h, tests/unittests/mocks/SdBusMock.h
This reorganizes the layers of abstraction in the sense how `Message` depends on `Connection` and vice versa. Now, `Message` has a link to the `Connection`. This replaces the shortcut link to the low-level `SdBus` interface that the `Message` kept. The interactions from `Message` now go through `Connection` which forwards them to `SdBus`. `Connection` is now a sole owner of the low-level `SdBus` interface. This allows for future changes around `SdBus` (e.g. a change from virtual functions back to non-virtual functions) without affecting the rest of the library. `Proxy`s and `Object`s can now send messages directly without having to go through `Connection`. The `Connection` no more depends on `Message` business-logic methods; it serves only as a factory for messages.
The flow for creating …
=> refactor: invert dependency between Message and Connection

tools/CMakeLists.txt, tools/xml2cpp-codegen/xml2cpp.cpp
Adds the `-v, --version` command line tool options to the `xml2cpp` tool.
Closes https://github.com/Kistler-Group/sdbus-cpp/issues/460 
Usage:
```bash
$ ./sdbus-c++-xml2cpp --version
Version: 2.0.0
```
```bash
$ ./sdbus-c++-xml2cpp -v
Version: 2.0.0
```
=> Added -v, --version command line tool options to xml2cpp 

docs/using-sdbus-c++.md, include/sdbus-c++/Message.h, include/sdbus-c++/TypeTraits.h, include/sdbus-c++/Types.h, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/TestAdaptor.cpp, tests/integrationtests/TestAdaptor.h, tests/integrationtests/integrationtests-adaptor.h, tests/unittests/Message_test.cpp
This extends the functionality of `SDBUSCPP_REGISTER_STRUCT` macro.
It now provides functionality for serializing a user-defined struct as an `a{sv}` dictionary, and for deserializing an `a{sv}` dictionary into a user-defined struct. The former one is achieved by decorating the struct with `sdbus::as_dictionary(struct)`, the latter one is an automatic behavior -- when sdbus-c++ is asked to deserialize into a struct but the data in the message is of type `a{sv}`, then the dict-to-struct deserialization is performed automatically.
There are some aspects of behavior in the serialization/deserialization functionality that can be customized by the client. Newly introduced `SDBUSCPP_ENABLE_NESTED_STRUCT2DICT_SERIALIZATION` and `SDBUSCPP_ENABLE_RELAXED_DICT2STRUCT_DESERIALIZATION` macros serve …
=> feat: introduce support for struct<->dict (de)serialization

include/sdbus-c++/TypeTraits.h, include/sdbus-c++/Types.h, tests/integrationtests/DBusPropertiesTests.cpp, tests/integrationtests/DBusStandardInterfacesTests.cpp, tests/integrationtests/Defs.h, tests/integrationtests/TestAdaptor.cpp, tests/integrationtests/TestAdaptor.h, tests/integrationtests/integrationtests-adaptor.h, tests/integrationtests/integrationtests-proxy.h, tools/xml2cpp-codegen/ProxyGenerator.cpp
This allows nesting variants, i.e. allows a variant to contain another variant as its value. Until now, there was no such possibility, since the default generated copy constructor would be invoked which would create a copy of source variant instead of embed the source variant as a value in the destination variant. The default generated copy constructor is kept, for it makes sense too, but a new tag-based overload is added for embedding the source variant into the destination variant.
Fixes #468
=> fix: add missing c-tor for nesting Variants

tools/xml2cpp-codegen/AdaptorGenerator.cpp
Before the patch, generating an adaptor from https://gitlab.freedesktop.org/hadess/mpris-spec/-/blob/master/spec/org.mpris.MediaPlayer2.xml would produce incorrect code like this:
```
m_object.addVTable( sdbus::setInterfaceFlags().withPropertyUpdateBehavior(sdbus::Flags::EMITS_CHANGE_SIGNAL);
, sdbus::registerMethod("Raise").implementedAs([this](){ return this->Raise(); })
, sdbus::registerMethod("Quit").implementedAs([this](){ return this->Quit(); })
...
```
With this patch, the code produced is:
```
m_object.addVTable( sdbus::setInterfaceFlags().withPropertyUpdateBehavior(sdbus::Flags::EMITS_CHANGE_SIGNAL)
, sdbus::registerMethod("Raise").implementedAs([this](){ return this->Raise(); })
, sdbus::registerMethod("Quit").implementedAs([this](){ return this->Quit(); })
...
```
=> This patch fixes the annotation registration generated code.

include/sdbus-c++/Message.h, src/Message.cpp, tests/integrationtests/DBusMethodsTests.cpp, tests/integrationtests/TestFixture.h, tests/integrationtests/TestProxy.cpp, tests/integrationtests/TestProxy.h
Add `sd_bus_message_get_cookie()` and `sd_bus_message_get_reply_cookie()` as `Message::getCookie()` and `Message::getReplyCookie()`.
=> feat: Add sd_bus_message_get_cookie (#490)

.github/workflows/ci.yml, include/sdbus-c++/StandardInterfaces.h, tests/integrationtests/DBusStandardInterfacesTests.cpp
Adds the following to Standardinterfaces.h
```
template <typename _Function>
PendingAsyncCall GetManagedObjectsAync(_Function&& callback)
{
std::map<sdbus::ObjectPath, std::map<sdbus::InterfaceName, std::map<PropertyName, sdbus::Variant>>> objectsInterfacesAndProperties;
return m_proxy.callMethodAsync("GetManagedObjects").onInterface(INTERFACE_NAME).uponReplyInvoke(std::forward<_Function>(callback));
}
std::future<std::map<sdbus::ObjectPath, std::map<sdbus::InterfaceName, std::map<PropertyName, sdbus::Variant>>>> GetManagedObjectsAync(with_future_t) const {
return m_proxy.callMethodAsync("GetManagedObjects").onInterface(INTERFACE_NAME).getResultAsFuture<std::map<sdbus::ObjectPath, std::map<sdbus::InterfaceName, std::map<PropertyName, sdbus::Variant>>>>();
}
```
=> feat: add async overloads of GetManagedObjects()
