Kistler-Group/sdbus-cpp

README.md

Add pkgconfig to Dependencies

---

include/sdbus-c++/Types.h
src/Message.cpp
tests/integrationtests/AdaptorAndProxy_test.cpp
tests/integrationtests/TestingAdaptor.h
tests/unittests/Message_test.cpp
tests/unittests/Types_test.cpp

Switch from plain UnixFd to owning UnixFd

---

docs/using-sdbus-c++.md
include/sdbus-c++/ConvenienceApiClasses.h
include/sdbus-c++/ConvenienceApiClasses.inl
include/sdbus-c++/IObject.h
src/Object.cpp
src/Object.h
src/VTableUtils.c
src/VTableUtils.h
tests/integrationtests/adaptor-glue.h
tests/perftests/perftests-adaptor.h
tests/stresstests/celsius-thermometer-adaptor.h
tests/stresstests/concatenator-adaptor.h
tests/stresstests/fahrenheit-thermometer-adaptor.h
tools/xml2cpp-codegen/AdaptorGenerator.cpp
tools/xml2cpp-codegen/BaseGenerator.cpp
tools/xml2cpp-codegen/BaseGenerator.h
tools/xml2cpp-codegen/ProxyGenerator.cpp

Implement support for method and signal parameter names in introspection

---

include/sdbus-c++/ConvenienceApiClasses.h
include/sdbus-c++/ConvenienceApiClasses.inl
include/sdbus-c++/IProxy.h
src/Proxy.cpp
src/Proxy.h
tests/integrationtests/AdaptorAndProxy_test.cpp
tests/integrationtests/proxy-glue.h
tests/stresstests/concatenator-proxy.h
tools/xml2cpp-codegen/ProxyGenerator.cpp

Add support for cancellable async D-Bus calls

---

include/sdbus-c++/IProxy.h

* Add missing PendingAsyncCall return value to relevant IProxy::callMethod() overload

Fixup for 00d0837d985dcec32cd8446e8a4f701e5370083f

---

include/sdbus-c++/AdaptorInterfaces.h
include/sdbus-c++/IObject.h
include/sdbus-c++/IProxy.h
include/sdbus-c++/ProxyInterfaces.h
src/Object.cpp
src/Object.h
src/Proxy.cpp
src/Proxy.h

is @brief enough or should something more added?

Implement #104: add getObjectPath() for classes

---

include/sdbus-c++/Message.h
src/ISdBus.h
src/Message.cpp
src/SdBus.cpp
src/SdBus.h
tests/unittests/mocks/SdBusMock.h

Signed-off-by: Alexander Livenets <a.livenets@gmail.com>

sdbus-cpp: Add API to get message credentials

---

CMakeLists.txt

reformat CMake linking

---

include/sdbus-c++/ConvenienceApiClasses.inl

This change addresses conditions where an exception is thrown by the library upon receipt of a malformed message from an external source, and propagated up to the event loop with no chance of interception by the application. This issue is only experienced by proxy convenience APIs, as low-level APIs allow the application to unpack the message.
Strategy:
1. For malformed signals received by proxies: ignore the signal.
2. For malformed async method responses, translate the unpack exception into an sdbus::Error, and pass it to the caller as expected.

Avoid propagating msg unpack exceptions to event loop

---

src/Object.cpp
src/Object.h

This mirrors https://github.com/Kistler-Group/sdbus-cpp/pull/177.
Fixes #189

Fix potential race condition in Object destruction

---

ChangeLog

update ChangeLog: v0.8.4 was never released

---

include/sdbus-c++/Error.h
tests/unittests/Types_test.cpp

See https://github.com/Kistler-Group/sdbus-cpp/issues/231

Fix potential UB in creation of sdbus::Error.

---

CMakeLists.txt
src/Connection.cpp
src/Object.cpp
src/Proxy.cpp
src/Utils.h

Fixes #144 
/cc @hellow554 @Oxymoron79

refactor: add validity checks for names and paths

---

tools/xml2cpp-codegen/generator_utils.cpp

fix: detect missing type after array declaration

---

docs/systemd-dbus-config.md
docs/using-sdbus-c++.md

docs: add more info on D-Bus security policy file

---

include/sdbus-c++/IConnection.h
include/sdbus-c++/Message.h
include/sdbus-c++/TypeTraits.h
include/sdbus-c++/Types.h
src/Connection.cpp
src/Connection.h
src/IConnection.h
src/Message.cpp
src/Object.cpp
src/Object.h
src/Proxy.cpp
src/Proxy.h

This fixes #251 and does a little refactoring/reorganization/unification of some pieces of code around Connection class, partly as a preparation for the upcoming PR.
Thank you @dleeds-cpi for pointing to the issue.

refactor: little fixes and reorganizations around Connection class

---

docs/using-sdbus-c++.md

I had to deal with some type problems and wrote a short D-Bus to C++ type table. Added it because it adresses open issue #204.
Fixes #204

Added D-Bus type C++ type table

---

README.md

- D-Bus specification broken url link is corrected
Signed-off-by: Bhavith C <bhavithc.acharya@gmail.com>

Fix: Fix the broken link

---

cmake/LibsystemdExternalProject.cmake
tests/integrationtests/DBusStandardInterfacesTests.cpp

fix: integration tests for libsystemd v251

---

docs/using-sdbus-c++.md

Now it's part of official sdbus-c++ documentation that type mappings are extensible by clients. This PR adds a new section into the tutorial on how to extend sdbus-c++ type system, so sdbus-c++ can convert them to/from D-Bus types.

docs: add tutorial on extending sdbus-c++ types

---

include/sdbus-c++/TypeTraits.h
tests/unittests/Message_test.cpp

This adds new unit tests are added to demonstrate and verify that [type extensibility](#346) works.

test: add tests for type extensibility

---

docs/using-sdbus-c++.md
include/sdbus-c++/ConvenienceApiClasses.h
include/sdbus-c++/ConvenienceApiClasses.inl
include/sdbus-c++/IProxy.h
include/sdbus-c++/StandardInterfaces.h
include/sdbus-c++/TypeTraits.h
tests/integrationtests/DBusStandardInterfacesTests.cpp
tools/xml2cpp-codegen/ProxyGenerator.cpp
tools/xml2cpp-codegen/ProxyGenerator.h

feat: add support for async property get/set on client-side

---

.github/workflows/ci.yml
CMakeLists.txt
src/Connection.cpp
src/Connection.h
src/Error.cpp
src/Flags.cpp
src/IConnection.h
src/ISdBus.h
src/Message.cpp
src/Object.cpp
src/Object.h
src/Proxy.cpp
src/Proxy.h
src/SdBus.cpp
src/Types.cpp
src/Utils.h
src/VTableUtils.c
src/VTableUtils.h
tests/CMakeLists.txt
tests/integrationtests/DBusMethodsTests.cpp
tests/integrationtests/DBusStandardInterfacesTests.cpp

Tested [downstream](https://www.freshports.org/devel/sdbus-cpp) via [pass-secrets](https://github.com/nullobsi/pass-secrets) and [xdg-desktop-portal-hyprland](https://github.com/hyprwm/xdg-desktop-portal-hyprland).

Add FreeBSD support

---

.github/workflows/ci.yml

See https://github.com/vmactions/freebsd-vm/issues/74

chore(ci): run freebsd job on ubuntu (to improve stability)

---

CMakeLists.txt
pkgconfig/sdbus-c++.pc.in
tests/CMakeLists.txt

fix: correctly add libsystemd dependency to pkgconfig

---

src/Connection.cpp

fix: request name signal handling issue

---

docs/using-sdbus-c++.md
examples/org.freedesktop.DBus.ObjectManager/examplemanager-planet1-client-glue.h
include/sdbus-c++/ConvenienceApiClasses.h
include/sdbus-c++/ConvenienceApiClasses.inl
include/sdbus-c++/IProxy.h
include/sdbus-c++/ProxyInterfaces.h
include/sdbus-c++/StandardInterfaces.h
src/Connection.cpp
src/Connection.h
src/IConnection.h
src/Proxy.cpp
src/Proxy.h
tests/integrationtests/integrationtests-proxy.h
tests/perftests/perftests-proxy.h
tests/stresstests/celsius-thermometer-proxy.h
tests/stresstests/concatenator-proxy.h
tests/stresstests/fahrenheit-thermometer-proxy.h
tools/xml2cpp-codegen/ProxyGenerator.cpp

refactor: improve Proxy signal subscription

---

CMakeLists.txt
include/sdbus-c++/IObject.h
include/sdbus-c++/IProxy.h

chore: reorder some API functions

---

docs/using-sdbus-c++.md
examples/org.freedesktop.DBus.ObjectManager/examplemanager-planet1-client-glue.h
examples/org.freedesktop.DBus.ObjectManager/examplemanager-planet1-server-glue.h
include/sdbus-c++/AdaptorInterfaces.h
include/sdbus-c++/ProxyInterfaces.h
include/sdbus-c++/StandardInterfaces.h
tests/integrationtests/DBusGeneralTests.cpp
tests/integrationtests/integrationtests-adaptor.h
tests/integrationtests/integrationtests-proxy.h
tests/perftests/perftests-adaptor.h
tests/perftests/perftests-proxy.h
tests/stresstests/celsius-thermometer-adaptor.h
tests/stresstests/celsius-thermometer-proxy.h
tests/stresstests/concatenator-adaptor.h
tests/stresstests/concatenator-proxy.h
tests/stresstests/fahrenheit-thermometer-adaptor.h
tests/stresstests/fahrenheit-thermometer-proxy.h
tools/xml2cpp-codegen/AdaptorGenerator.cpp
tools/xml2cpp-codegen/ProxyGenerator.cpp

fix: disable move in generated adaptor and proxy classes

---

tools/xml2cpp-codegen/BaseGenerator.cpp
tools/xml2cpp-codegen/xml2cpp.cpp

Check for output file failure, and error exit in that case
